// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_thy1s4qq2jTqrYWEktYCjXIvUTwdu4',
    appId: '1:875543380570:web:725effe5b897eeaaf98e63',
    messagingSenderId: '875543380570',
    projectId: 'final-project-62656',
    authDomain: 'final-project-62656.firebaseapp.com',
    storageBucket: 'final-project-62656.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFFWMShSQu5YOsUyNbfLOuykUdLIds3Q',
    appId: '1:875543380570:android:a1abbd9e9507c329f98e63',
    messagingSenderId: '875543380570',
    projectId: 'final-project-62656',
    storageBucket: 'final-project-62656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyTzs5w2NpardNnZc1Om2Q8A15YKwa7Y',
    appId: '1:875543380570:ios:220c80410598795df98e63',
    messagingSenderId: '875543380570',
    projectId: 'final-project-62656',
    storageBucket: 'final-project-62656.appspot.com',
    iosClientId: '875543380570-mqs2ic47g757u9qvm52lfvbk5n6a28f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
